import type { Zone } from '../types'

export interface Country {
  slug: string
  flag: string
  zone: Zone
}

export const ALL_COUNTRIES: Country[] = [
  // ── Schengen (29) ────────────────────────────────────────────────────────
  { slug: 'austria',         flag: '🇦🇹', zone: 'schengen' },
  { slug: 'belgium',         flag: '🇧🇪', zone: 'schengen' },
  { slug: 'bulgaria',        flag: '🇧🇬', zone: 'schengen' },
  { slug: 'croatia',         flag: '🇭🇷', zone: 'schengen' },
  { slug: 'czech_republic',  flag: '🇨🇿', zone: 'schengen' },
  { slug: 'denmark',         flag: '🇩🇰', zone: 'schengen' },
  { slug: 'estonia',         flag: '🇪🇪', zone: 'schengen' },
  { slug: 'finland',         flag: '🇫🇮', zone: 'schengen' },
  { slug: 'france',          flag: '🇫🇷', zone: 'schengen' },
  { slug: 'germany',         flag: '🇩🇪', zone: 'schengen' },
  { slug: 'greece',          flag: '🇬🇷', zone: 'schengen' },
  { slug: 'hungary',         flag: '🇭🇺', zone: 'schengen' },
  { slug: 'iceland',         flag: '🇮🇸', zone: 'schengen' },
  { slug: 'italy',           flag: '🇮🇹', zone: 'schengen' },
  { slug: 'latvia',          flag: '🇱🇻', zone: 'schengen' },
  { slug: 'liechtenstein',   flag: '🇱🇮', zone: 'schengen' },
  { slug: 'lithuania',       flag: '🇱🇹', zone: 'schengen' },
  { slug: 'luxembourg',      flag: '🇱🇺', zone: 'schengen' },
  { slug: 'malta',           flag: '🇲🇹', zone: 'schengen' },
  { slug: 'netherlands',     flag: '🇳🇱', zone: 'schengen' },
  { slug: 'norway',          flag: '🇳🇴', zone: 'schengen' },
  { slug: 'poland',          flag: '🇵🇱', zone: 'schengen' },
  { slug: 'portugal',        flag: '🇵🇹', zone: 'schengen' },
  { slug: 'romania',         flag: '🇷🇴', zone: 'schengen' },
  { slug: 'slovakia',        flag: '🇸🇰', zone: 'schengen' },
  { slug: 'slovenia',        flag: '🇸🇮', zone: 'schengen' },
  { slug: 'spain',           flag: '🇪🇸', zone: 'schengen' },
  { slug: 'sweden',          flag: '🇸🇪', zone: 'schengen' },
  { slug: 'switzerland',     flag: '🇨🇭', zone: 'schengen' },

  // ── Tracked single-country zones ─────────────────────────────────────────
  { slug: 'united_kingdom',       flag: '🇬🇧', zone: 'uk' },
  { slug: 'united_states',        flag: '🇺🇸', zone: 'usa' },
  { slug: 'turkey',               flag: '🇹🇷', zone: 'turkey' },
  { slug: 'united_arab_emirates', flag: '🇦🇪', zone: 'uae' },
  { slug: 'thailand',             flag: '🇹🇭', zone: 'thailand' },
  { slug: 'georgia',              flag: '🇬🇪', zone: 'georgia' },

  // ── Europe (non-Schengen) ─────────────────────────────────────────────────
  { slug: 'albania',                flag: '🇦🇱', zone: 'other' },
  { slug: 'andorra',                flag: '🇦🇩', zone: 'other' },
  { slug: 'belarus',                flag: '🇧🇾', zone: 'other' },
  { slug: 'bosnia_and_herzegovina', flag: '🇧🇦', zone: 'other' },
  { slug: 'kosovo',                 flag: '🇽🇰', zone: 'other' },
  { slug: 'moldova',                flag: '🇲🇩', zone: 'other' },
  { slug: 'monaco',                 flag: '🇲🇨', zone: 'other' },
  { slug: 'montenegro',             flag: '🇲🇪', zone: 'other' },
  { slug: 'north_macedonia',        flag: '🇲🇰', zone: 'other' },
  { slug: 'russia',                 flag: '🇷🇺', zone: 'other' },
  { slug: 'san_marino',             flag: '🇸🇲', zone: 'other' },
  { slug: 'serbia',                 flag: '🇷🇸', zone: 'other' },
  { slug: 'ukraine',                flag: '🇺🇦', zone: 'other' },
  { slug: 'vatican',                flag: '🇻🇦', zone: 'other' },

  // ── Asia ─────────────────────────────────────────────────────────────────
  { slug: 'afghanistan',  flag: '🇦🇫', zone: 'other' },
  { slug: 'armenia',      flag: '🇦🇲', zone: 'other' },
  { slug: 'azerbaijan',   flag: '🇦🇿', zone: 'other' },
  { slug: 'bahrain',      flag: '🇧🇭', zone: 'other' },
  { slug: 'bangladesh',   flag: '🇧🇩', zone: 'other' },
  { slug: 'bhutan',       flag: '🇧🇹', zone: 'other' },
  { slug: 'brunei',       flag: '🇧🇳', zone: 'other' },
  { slug: 'cambodia',     flag: '🇰🇭', zone: 'other' },
  { slug: 'china',        flag: '🇨🇳', zone: 'other' },
  { slug: 'india',        flag: '🇮🇳', zone: 'other' },
  { slug: 'indonesia',    flag: '🇮🇩', zone: 'other' },
  { slug: 'iran',         flag: '🇮🇷', zone: 'other' },
  { slug: 'iraq',         flag: '🇮🇶', zone: 'other' },
  { slug: 'israel',       flag: '🇮🇱', zone: 'other' },
  { slug: 'japan',        flag: '🇯🇵', zone: 'other' },
  { slug: 'jordan',       flag: '🇯🇴', zone: 'other' },
  { slug: 'kazakhstan',   flag: '🇰🇿', zone: 'other' },
  { slug: 'kuwait',       flag: '🇰🇼', zone: 'other' },
  { slug: 'kyrgyzstan',   flag: '🇰🇬', zone: 'other' },
  { slug: 'laos',         flag: '🇱🇦', zone: 'other' },
  { slug: 'lebanon',      flag: '🇱🇧', zone: 'other' },
  { slug: 'malaysia',     flag: '🇲🇾', zone: 'other' },
  { slug: 'maldives',     flag: '🇲🇻', zone: 'other' },
  { slug: 'mongolia',     flag: '🇲🇳', zone: 'other' },
  { slug: 'myanmar',      flag: '🇲🇲', zone: 'other' },
  { slug: 'nepal',        flag: '🇳🇵', zone: 'other' },
  { slug: 'north_korea',  flag: '🇰🇵', zone: 'other' },
  { slug: 'oman',         flag: '🇴🇲', zone: 'other' },
  { slug: 'pakistan',     flag: '🇵🇰', zone: 'other' },
  { slug: 'palestine',    flag: '🇵🇸', zone: 'other' },
  { slug: 'philippines',  flag: '🇵🇭', zone: 'other' },
  { slug: 'qatar',        flag: '🇶🇦', zone: 'other' },
  { slug: 'saudi_arabia', flag: '🇸🇦', zone: 'other' },
  { slug: 'singapore',    flag: '🇸🇬', zone: 'other' },
  { slug: 'south_korea',  flag: '🇰🇷', zone: 'other' },
  { slug: 'sri_lanka',    flag: '🇱🇰', zone: 'other' },
  { slug: 'syria',        flag: '🇸🇾', zone: 'other' },
  { slug: 'taiwan',       flag: '🇹🇼', zone: 'other' },
  { slug: 'tajikistan',   flag: '🇹🇯', zone: 'other' },
  { slug: 'timor_leste',  flag: '🇹🇱', zone: 'other' },
  { slug: 'turkmenistan', flag: '🇹🇲', zone: 'other' },
  { slug: 'uzbekistan',   flag: '🇺🇿', zone: 'other' },
  { slug: 'vietnam',      flag: '🇻🇳', zone: 'other' },
  { slug: 'yemen',        flag: '🇾🇪', zone: 'other' },

  // ── Africa ────────────────────────────────────────────────────────────────
  { slug: 'algeria',                 flag: '🇩🇿', zone: 'other' },
  { slug: 'angola',                  flag: '🇦🇴', zone: 'other' },
  { slug: 'benin',                   flag: '🇧🇯', zone: 'other' },
  { slug: 'botswana',                flag: '🇧🇼', zone: 'other' },
  { slug: 'burkina_faso',            flag: '🇧🇫', zone: 'other' },
  { slug: 'burundi',                 flag: '🇧🇮', zone: 'other' },
  { slug: 'cameroon',                flag: '🇨🇲', zone: 'other' },
  { slug: 'cape_verde',              flag: '🇨🇻', zone: 'other' },
  { slug: 'central_african_republic',flag: '🇨🇫', zone: 'other' },
  { slug: 'chad',                    flag: '🇹🇩', zone: 'other' },
  { slug: 'comoros',                 flag: '🇰🇲', zone: 'other' },
  { slug: 'congo',                   flag: '🇨🇬', zone: 'other' },
  { slug: 'dr_congo',                flag: '🇨🇩', zone: 'other' },
  { slug: 'djibouti',                flag: '🇩🇯', zone: 'other' },
  { slug: 'egypt',                   flag: '🇪🇬', zone: 'other' },
  { slug: 'equatorial_guinea',       flag: '🇬🇶', zone: 'other' },
  { slug: 'eritrea',                 flag: '🇪🇷', zone: 'other' },
  { slug: 'eswatini',                flag: '🇸🇿', zone: 'other' },
  { slug: 'ethiopia',                flag: '🇪🇹', zone: 'other' },
  { slug: 'gabon',                   flag: '🇬🇦', zone: 'other' },
  { slug: 'gambia',                  flag: '🇬🇲', zone: 'other' },
  { slug: 'ghana',                   flag: '🇬🇭', zone: 'other' },
  { slug: 'guinea',                  flag: '🇬🇳', zone: 'other' },
  { slug: 'guinea_bissau',           flag: '🇬🇼', zone: 'other' },
  { slug: 'ivory_coast',             flag: '🇨🇮', zone: 'other' },
  { slug: 'kenya',                   flag: '🇰🇪', zone: 'other' },
  { slug: 'lesotho',                 flag: '🇱🇸', zone: 'other' },
  { slug: 'liberia',                 flag: '🇱🇷', zone: 'other' },
  { slug: 'libya',                   flag: '🇱🇾', zone: 'other' },
  { slug: 'madagascar',              flag: '🇲🇬', zone: 'other' },
  { slug: 'malawi',                  flag: '🇲🇼', zone: 'other' },
  { slug: 'mali',                    flag: '🇲🇱', zone: 'other' },
  { slug: 'mauritania',              flag: '🇲🇷', zone: 'other' },
  { slug: 'mauritius',               flag: '🇲🇺', zone: 'other' },
  { slug: 'morocco',                 flag: '🇲🇦', zone: 'other' },
  { slug: 'mozambique',              flag: '🇲🇿', zone: 'other' },
  { slug: 'namibia',                 flag: '🇳🇦', zone: 'other' },
  { slug: 'niger',                   flag: '🇳🇪', zone: 'other' },
  { slug: 'nigeria',                 flag: '🇳🇬', zone: 'other' },
  { slug: 'rwanda',                  flag: '🇷🇼', zone: 'other' },
  { slug: 'sao_tome_and_principe',   flag: '🇸🇹', zone: 'other' },
  { slug: 'senegal',                 flag: '🇸🇳', zone: 'other' },
  { slug: 'seychelles',              flag: '🇸🇨', zone: 'other' },
  { slug: 'sierra_leone',            flag: '🇸🇱', zone: 'other' },
  { slug: 'somalia',                 flag: '🇸🇴', zone: 'other' },
  { slug: 'south_africa',            flag: '🇿🇦', zone: 'other' },
  { slug: 'south_sudan',             flag: '🇸🇸', zone: 'other' },
  { slug: 'sudan',                   flag: '🇸🇩', zone: 'other' },
  { slug: 'tanzania',                flag: '🇹🇿', zone: 'other' },
  { slug: 'togo',                    flag: '🇹🇬', zone: 'other' },
  { slug: 'tunisia',                 flag: '🇹🇳', zone: 'other' },
  { slug: 'uganda',                  flag: '🇺🇬', zone: 'other' },
  { slug: 'zambia',                  flag: '🇿🇲', zone: 'other' },
  { slug: 'zimbabwe',                flag: '🇿🇼', zone: 'other' },

  // ── Americas ──────────────────────────────────────────────────────────────
  { slug: 'antigua_and_barbuda',             flag: '🇦🇬', zone: 'other' },
  { slug: 'argentina',                       flag: '🇦🇷', zone: 'other' },
  { slug: 'bahamas',                         flag: '🇧🇸', zone: 'other' },
  { slug: 'barbados',                        flag: '🇧🇧', zone: 'other' },
  { slug: 'belize',                          flag: '🇧🇿', zone: 'other' },
  { slug: 'bolivia',                         flag: '🇧🇴', zone: 'other' },
  { slug: 'brazil',                          flag: '🇧🇷', zone: 'other' },
  { slug: 'canada',                          flag: '🇨🇦', zone: 'other' },
  { slug: 'chile',                           flag: '🇨🇱', zone: 'other' },
  { slug: 'colombia',                        flag: '🇨🇴', zone: 'other' },
  { slug: 'costa_rica',                      flag: '🇨🇷', zone: 'other' },
  { slug: 'cuba',                            flag: '🇨🇺', zone: 'other' },
  { slug: 'dominica',                        flag: '🇩🇲', zone: 'other' },
  { slug: 'dominican_republic',              flag: '🇩🇴', zone: 'other' },
  { slug: 'ecuador',                         flag: '🇪🇨', zone: 'other' },
  { slug: 'el_salvador',                     flag: '🇸🇻', zone: 'other' },
  { slug: 'grenada',                         flag: '🇬🇩', zone: 'other' },
  { slug: 'guatemala',                       flag: '🇬🇹', zone: 'other' },
  { slug: 'guyana',                          flag: '🇬🇾', zone: 'other' },
  { slug: 'haiti',                           flag: '🇭🇹', zone: 'other' },
  { slug: 'honduras',                        flag: '🇭🇳', zone: 'other' },
  { slug: 'jamaica',                         flag: '🇯🇲', zone: 'other' },
  { slug: 'mexico',                          flag: '🇲🇽', zone: 'other' },
  { slug: 'nicaragua',                       flag: '🇳🇮', zone: 'other' },
  { slug: 'panama',                          flag: '🇵🇦', zone: 'other' },
  { slug: 'paraguay',                        flag: '🇵🇾', zone: 'other' },
  { slug: 'peru',                            flag: '🇵🇪', zone: 'other' },
  { slug: 'saint_kitts_and_nevis',           flag: '🇰🇳', zone: 'other' },
  { slug: 'saint_lucia',                     flag: '🇱🇨', zone: 'other' },
  { slug: 'saint_vincent_and_the_grenadines',flag: '🇻🇨', zone: 'other' },
  { slug: 'suriname',                        flag: '🇸🇷', zone: 'other' },
  { slug: 'trinidad_and_tobago',             flag: '🇹🇹', zone: 'other' },
  { slug: 'uruguay',                         flag: '🇺🇾', zone: 'other' },
  { slug: 'venezuela',                       flag: '🇻🇪', zone: 'other' },

  // ── Oceania ───────────────────────────────────────────────────────────────
  { slug: 'australia',        flag: '🇦🇺', zone: 'other' },
  { slug: 'fiji',             flag: '🇫🇯', zone: 'other' },
  { slug: 'kiribati',         flag: '🇰🇮', zone: 'other' },
  { slug: 'marshall_islands', flag: '🇲🇭', zone: 'other' },
  { slug: 'micronesia',       flag: '🇫🇲', zone: 'other' },
  { slug: 'nauru',            flag: '🇳🇷', zone: 'other' },
  { slug: 'new_zealand',      flag: '🇳🇿', zone: 'other' },
  { slug: 'palau',            flag: '🇵🇼', zone: 'other' },
  { slug: 'papua_new_guinea', flag: '🇵🇬', zone: 'other' },
  { slug: 'samoa',            flag: '🇼🇸', zone: 'other' },
  { slug: 'solomon_islands',  flag: '🇸🇧', zone: 'other' },
  { slug: 'tonga',            flag: '🇹🇴', zone: 'other' },
  { slug: 'tuvalu',           flag: '🇹🇻', zone: 'other' },
  { slug: 'vanuatu',          flag: '🇻🇺', zone: 'other' },
]

export const COUNTRY_FLAGS: Record<string, string> = Object.fromEntries(
  ALL_COUNTRIES.map((c) => [c.slug, c.flag])
)

export const COUNTRY_ZONE: Record<string, Zone> = Object.fromEntries(
  ALL_COUNTRIES.map((c) => [c.slug, c.zone])
)

export const SCHENGEN_COUNTRIES = ALL_COUNTRIES.filter((c) => c.zone === 'schengen')
